#Repository = text
#Patients = patients.txt
#Appointments = appointments.txt
Repository=db
#Patients = patients.db
#Appointments = appointments.db

#Repository = binary
#Patients = patients.bin
#Appointments = appointments.bin